#!/usr/bin/php
<?php

$bootsrapFiles = array(
    __DIR__ . '/bootstrap.php',
    __DIR__ . '/../../vendor/bruli/php-git-hooks/hooks/bootstrap.php',
    __DIR__ . '/../../hooks/bootstrap.php'
);

foreach ($bootsrapFiles as $file) {
    if (file_exists($file)) {
        define('PHPGITHOOKS_BOOTSTRAP', $file);
        break;
    }
}

unset($bootsrapFiles, $file);

if (false === defined('PHPGITHOOKS_BOOTSTRAP')) {
    fwrite(
        STDERR,
        'Bootstrap not found, you can submit an issue and blame @tophsic ;), see PR #30'
    );

    die(1);
}

require PHPGITHOOKS_BOOTSTRAP;

use PhpGitHooks\Command\QualityMessageTool;

$console = new QualityMessageTool();
$console->run();
