#!/usr/bin/php
<?php

$bootsrapFiles = array(
    __DIR__ . '/bootstrap.php',
    __DIR__ . '/../../vendor/bruli/php-git-hooks/hooks/bootstrap.php'
);

foreach ($bootsrapFiles as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use PhpGitHooks\Command\QualityMessageTool;

$console = new QualityMessageTool();
$console->run();
