#!/usr/bin/env php
<?php

require __DIR__ . '/../../vendor/autoload.php';

use PhpGitHooks\Container;

$container = new Container();

$tool = $container->get('tool.pre-commit');
$tool->setContainer($container);
$tool->run();
